The user wants me to pick a difficult LeetCode problem that is NOT in the given list and solve it in C++.

The existing problems are:
1. Minimum Number of Pushes to Type Word II (LeetCode 3014)
2. Smallest_Palindromic_Rearrangement_II (likely a variation or specific problem, maybe not standard LeetCode name)
3. Put Marbles in Bags (LeetCode 2551)
4. watermelon (Codeforces 4A, not LeetCode)
5. Minimum Number of Pushes to Type Word (LeetCode 3016)
6. largest almost missing number (likely a custom or specific problem)

I need to pick a DIFFICULT LeetCode problem (Hard difficulty preferably) not in this list.

Good candidates:
- LeetCode 2391: Minimum Amount of Time to Collect Garbage (Medium)
- LeetCode 2542: Maximum Subsequence Score (Medium)
- LeetCode 2654: Minimum Number of Operations to Make All Array Elements Equal to 1 (Hard)
- LeetCode 2699: Modify Graph Edge Weights (Hard)
- LeetCode 2751: Robot Collisions (Hard)
- LeetCode 2812: Find the Safest Path in a Grid (Medium/Hard)
- LeetCode 2867: Count Valid Paths in a Tree (Hard)
- LeetCode 2952: Minimum Number of Coins to be Added (Hard)
- LeetCode 3003: Maximize the Number of Partitions After Operations (Hard)
- LeetCode 3027: Find the Number of Ways to Place People II (Hard)
- LeetCode 3097: Shortest Subarray With OR at Least K II (Hard)
- LeetCode 3106: Lexicographically Smallest String After Operations With Constraint (Hard)
- LeetCode 3143: Maximum Points Inside the Square (Medium)
- LeetCode 3169: Count Days Without Meetings (Medium)
- LeetCode 3170: Lexicographically Minimum String After Removing Stars (Medium)
- LeetCode 3192: Minimum Operations to Make Binary Array Elements Equal to One I (Medium)
- LeetCode 3193: Minimum Operations to Make Binary Array Elements Equal to One II (Hard)
- LeetCode 3203: Find Minimum Diameter After Merging Two Trees (Hard)
- LeetCode 3213: Construct String with Minimum Cost (Hard)
- LeetCode 3218: Minimum Cost for Cutting Cake I (Medium)
- LeetCode 3219: Minimum Cost for Cutting Cake II (Hard)
- LeetCode 3222: Find the Winning Player in Coin Game (Medium)
- LeetCode 3223: Minimum Length of String After Operations (Hard)
- LeetCode 3233: Find the Count of Numbers Which Are Not Special (Medium)
- LeetCode 3242: Design Neighbor Sum Service (Easy)
- LeetCode 3243: Shortest Distance After Road Addition Queries I (Medium)
- LeetCode 3244: Shortest Distance After Road Addition Queries II (Hard)
- LeetCode 3248: Snake in Matrix (Easy)
- LeetCode 3254: Find the Power of K-Size Subarrays I (Medium)
- LeetCode 3255: Find the Power of K-Size Subarrays II (Hard)
- LeetCode 3258: Count Substrings That Satisfy K-Constraint I (Medium)
- LeetCode 3259: Count Substrings That Satisfy K-Constraint II (Hard)
- LeetCode 3264: Final Array State After K Multiplication Operations I (Medium)
- LeetCode 3265: Final Array State After K Multiplication Operations II (Hard)
- LeetCode 3266: Final Array State After K Multiplication Operations III (Hard)
- LeetCode 3272: Find the Count of Good Integers (Hard)
- LeetCode 3273: Minimum Amount of Damage Dealt to Bob (Hard)
- LeetCode 3274: Check if Two Chessboard Squares Have the Same Color (Easy)
- LeetCode 3275: K-th Nearest Obstacle Queries (Medium)
- LeetCode 3276: Select Cells in Grid With Maximum Score (Hard)
- LeetCode 3277: Maximum XOR Score Subarray Queries (Hard)
- LeetCode 3278: Find the Candidate With Maximum Votes (Easy)
- LeetCode 3279: Minimum Number of Operations to Make Array XOR Equal to K (Easy)
- LeetCode 3280: Convert Date to Binary (Easy)
- LeetCode 3281: Maximize Score of Numbers in Ranges (Medium)
- LeetCode 3282: Reach End of Array With Max Score (Medium)
- LeetCode 3283: Maximum Number of Moves to Kill All Pawns (Medium)
- LeetCode 3284: Minimum Array Sum (Hard)
- LeetCode 3285: Find Indices of Stable Mountains (Easy)
- LeetCode 3286: Find a Safe Walk Through a Grid (Medium)
- LeetCode 3287: Find the Maximum Sequence Value of Array (Hard)
- LeetCode 3288: Find the Length of the Longest Increasing Path in a Matrix (Hard) - wait, this is 329?
- LeetCode 329: Longest Increasing Path in a Matrix (Hard)
- LeetCode 3290: Maximum Multiplication Score (Medium)
- LeetCode 3291: Minimum Number of Valid Strings to Form Target I (Medium)
- LeetCode 3292: Minimum Number of Valid Strings to Form Target II (Hard)
- LeetCode 3293: Minimum Number of Valid Strings to Form Target III (Hard)
- LeetCode 3294: Minimum Number of Valid Strings to Form Target IV (Hard)
- LeetCode 3295: Report Spam Message (Easy)
- LeetCode 3296: Minimum Number of Valid Strings to Form Target V (Hard)
- LeetCode 3297: Count Substrings That Can Be Rearranged to Contain a String I (Medium)
- LeetCode 3298: Count Substrings That Can Be Rearranged to Contain a String II (Hard)
- LeetCode 3299: Count Substrings That Can Be Rearranged to Contain a String III (Hard)
- LeetCode 3300: Minimum Element After Replacement With Digit Sum (Easy)
- LeetCode 3301: Maximize the Total Height of Unique Towers (Medium)
- LeetCode 3302: Find the Lexicographically Smallest Valid Sequence (Medium)
- LeetCode 3303: Find the Minimum Possible Sum of a Beautiful Array (Medium)
- LeetCode 3304: Find the K-th Character in String Game I (Easy)
- LeetCode 3305: Find the K-th Character in String Game II (Medium)
- LeetCode 3306: Count of Substrings Containing Every Vowel and K Consonants I (Medium)
- LeetCode 3307: Count of Substrings Containing Every Vowel and K Consonants II (Hard)
- LeetCode 3308: Find the K-th Character in String Game III (Hard)
- LeetCode 3309: Maximum Possible Number by Binary Concatenation (Medium)
- LeetCode 3310: Find the K-th Character in String Game IV (Hard)
- LeetCode 3311: Construct 2D Grid Matching Graph Layout (Medium)
- LeetCode 3312: Sorted GCD Pair Queries (Hard)
- LeetCode 3313: Find the Last Marked Nodes in Tree (Hard)
- LeetCode 3314: Construct the Minimum Bitwise Array I (Medium)
- LeetCode 3315: Construct the Minimum Bitwise Array II (Hard)
- LeetCode 3316: Find Maximum Removals From Source String (Medium)
- LeetCode 3317: Find the Number of Possible Ways to Reach Target (Hard)
- LeetCode 3318: Find X-Sum of All K-Subarrays (Medium)
- LeetCode 3319: K-th Largest Perfect Subtree Size in Binary Tree (Hard)
- LeetCode 3320: Count the Number of Winning Sequences (Hard)
- LeetCode 3321: Find X-Sum of All K-Subarrays II (Hard)
- LeetCode 3322: Find the Maximum Length of a Good Subsequence I (Medium)
- LeetCode 
